# Anything specific to making aarch64 work
packages:
  - grub2-efi
  - ostree-grub2
  - efibootmgr
  - shim

# The following packages are specified in a repo specific way.
# This prevents us from needing to use repo config priorities.
# Note: This is not necessary for "normal" packages, but will become useful for SIG packages,
# such as raspberry pi kernel. Doing it now sets a standard and documents the approach.
repo-packages:
  packages:
    - kernel
    - kernel-modules
    - kernel-modules-extra
  repo: baseos